/** Brand tool names shown on the homepage integrations strip. */
export const INTEGRATION_TOOLS = [
  "Make",
  "Zapier",
  "n8n",
  "Notion",
  "Airtable",
  "HubSpot",
  "Shopify",
  "Stripe",
  "Google Workspace",
  "WhatsApp",
  "Anthropic",
  "Supabase",
  "Figma",
  "Cursor",
  "Calendly",
  "Mailchimp",
  "QuickBooks",
  "Meta",
  "Facebook",
  "Instagram",
  "YouTube",
  "WordPress",
  "Vercel",
  "GitHub",
  "Cal.com",
] as const;
